import type { ItemTemplateField } from '@/lib/types/app'

export const itemTemplates: Record<string, ItemTemplateField[]> = {
  'personal-identity': [
    { key: 'document_type', label: 'Document Type', type: 'select',
      options: ['Birth Certificate', 'Passport', 'Social Security Card', 'Marriage Certificate',
                'Divorce Decree', 'Military Records', 'Citizenship Documents', 'Other'] },
    { key: 'document_number', label: 'Document Number', type: 'text', sensitive: true },
    { key: 'issuing_authority', label: 'Issuing Authority', type: 'text' },
    { key: 'issue_date', label: 'Issue Date', type: 'date' },
    { key: 'expiration_date', label: 'Expiration Date', type: 'date' },
    { key: 'location_stored', label: 'Where Is This Stored?', type: 'text' },
    { key: 'notes', label: 'Notes', type: 'textarea' },
  ],
  'family-relationships': [
    { key: 'person_name', label: 'Full Name', type: 'text' },
    { key: 'relationship', label: 'Relationship', type: 'text',
      placeholder: 'e.g., Son, Daughter, Stepchild, Sibling, Grandchild, Ex-spouse' },
    { key: 'phone', label: 'Phone', type: 'phone' },
    { key: 'email', label: 'Email', type: 'email' },
    { key: 'address', label: 'Address', type: 'text' },
    { key: 'date_of_birth', label: 'Date of Birth', type: 'date' },
    { key: 'relationship_notes', label: 'Relationship Notes', type: 'textarea',
      placeholder: 'Any context the family should know — estrangements, complications, special bonds' },
    { key: 'pet_info', label: 'Pet Information (if applicable)', type: 'textarea',
      placeholder: 'Name, breed, vet, care preferences, who takes the pet' },
    { key: 'notes', label: 'Notes', type: 'textarea' },
  ],
  'friends-neighbors': [
    { key: 'full_name', label: 'Full Name', type: 'text' },
    { key: 'relationship', label: 'Relationship', type: 'text',
      placeholder: 'e.g., Next door neighbor, Golf partner, Closest friend in community' },
    { key: 'phone', label: 'Phone', type: 'phone' },
    { key: 'email', label: 'Email', type: 'email' },
    { key: 'address', label: 'Address', type: 'text' },
    { key: 'proximity', label: 'How Close Do They Live?', type: 'select',
      options: ['Same street', 'Same community/building', 'Within 5 minutes', 'Within 15 minutes', 'Nearby'] },
    { key: 'has_key', label: 'Has a Key to Your Home?', type: 'boolean' },
    { key: 'has_gate_code', label: 'Has Gate/Community Access?', type: 'boolean' },
    { key: 'knows_health_conditions', label: 'Aware of Your Health Conditions?', type: 'boolean' },
    { key: 'authorized_welfare_check', label: 'Authorized for Welfare Checks?', type: 'boolean' },
    { key: 'emergency_priority', label: 'Emergency Contact Priority', type: 'select',
      options: ['Call first', 'Call second', 'Call third', 'Notify but not urgent'] },
    { key: 'best_contact_method', label: 'Best Way to Reach Them', type: 'select',
      options: ['Phone call', 'Text message', 'Email', 'In person'] },
    { key: 'notes', label: 'Notes', type: 'textarea' },
  ],
  'advisory-team': [
    { key: 'advisor_type', label: 'Type', type: 'select',
      options: ['Estate Planning Attorney', 'Business Attorney', 'CPA/Tax Advisor',
                'Wealth Manager', 'Financial Advisor', 'Insurance Agent', 'Banker',
                'Concierge Physician', 'Specialist', 'Pharmacist',
                'Property Manager', 'Trust Officer', 'Other'] },
    { key: 'name', label: 'Name', type: 'text' },
    { key: 'firm', label: 'Firm/Practice', type: 'text' },
    { key: 'phone', label: 'Phone', type: 'phone' },
    { key: 'email', label: 'Email', type: 'email' },
    { key: 'address', label: 'Address', type: 'text' },
    { key: 'specialty', label: 'Specialty/Focus', type: 'text' },
    { key: 'relationship_since', label: 'Client Since', type: 'text' },
    { key: 'notes', label: 'Notes', type: 'textarea' },
  ],
  'medical-history': [
    { key: 'record_type', label: 'Type', type: 'select',
      options: ['Current Diagnosis', 'Medication', 'Allergy', 'Physician/Specialist',
                'Medical Device', 'Pharmacy', 'Surgical History', 'HIPAA Authorization', 'Other'] },
    { key: 'name', label: 'Name/Description', type: 'text' },
    { key: 'details', label: 'Details', type: 'textarea',
      placeholder: 'Dosage, frequency, provider contact, model number — whatever is relevant' },
    { key: 'provider_name', label: 'Provider/Prescriber Name', type: 'text' },
    { key: 'provider_phone', label: 'Provider Phone', type: 'phone' },
    { key: 'date_started', label: 'Date Started/Diagnosed', type: 'date' },
    { key: 'notes', label: 'Notes', type: 'textarea' },
  ],
  'healthcare-preferences': [
    { key: 'preference_type', label: 'Type', type: 'select',
      options: ['Preferred Hospital', 'Preferred ER', 'Preferred Urgent Care',
                'Concierge/Primary Physician', 'Health System Preference',
                'DNR Status', 'Living Will Specifics', 'Organ Donation Wishes',
                'Pain Management Philosophy', 'Life-Sustaining Treatment Preferences',
                'Experimental Treatment Preferences', 'Religious/Spiritual Care',
                'Who Should Be Present', 'Who Should NOT Be Present',
                'Clergy/Spiritual Advisor to Contact', 'Comfort Items for Hospital', 'Other'] },
    { key: 'description', label: 'Description', type: 'textarea',
      placeholder: 'Describe this preference in your own words' },
    { key: 'facility_name', label: 'Facility/Provider Name', type: 'text' },
    { key: 'facility_phone', label: 'Phone', type: 'phone' },
    { key: 'facility_address', label: 'Address', type: 'text' },
    { key: 'document_location', label: 'Where Is the Related Document?', type: 'text' },
    { key: 'priority', label: 'Priority', type: 'select',
      options: ['Primary preference', 'Backup/alternate', 'General wish'] },
    { key: 'notes', label: 'Additional Notes', type: 'textarea' },
  ],
  'long-term-care': [
    { key: 'preference_type', label: 'Type', type: 'select',
      options: ['Preferred Care Setting', 'Specific Facility', 'Staffing Preference',
                'Non-Negotiable Requirement', 'Quality of Life Definition',
                'Transition Threshold', 'Geographic Preference', 'Dietary/Cultural Need', 'Other'] },
    { key: 'description', label: 'Description', type: 'textarea',
      placeholder: 'Describe in your own words what matters to you' },
    { key: 'ranking', label: 'Preference Ranking', type: 'select',
      options: ['First choice', 'Second choice', 'Third choice', 'Acceptable', 'Not acceptable'] },
    { key: 'facility_name', label: 'Facility Name (if specific)', type: 'text' },
    { key: 'facility_contact', label: 'Facility Contact Info', type: 'text' },
    { key: 'estimated_cost', label: 'Estimated Monthly Cost', type: 'text' },
    { key: 'notes', label: 'Notes', type: 'textarea' },
  ],
  'mental-health': [
    { key: 'topic', label: 'Topic', type: 'select',
      options: ['Cognitive Decline Wishes', 'Memory Care Preferences',
                'Activities That Bring Comfort', 'Music/Entertainment Preferences',
                'Daily Routines to Maintain', 'Things I Do NOT Want',
                'Who Decides / Trigger for Conversation', 'Mental Health History', 'Other'] },
    { key: 'description', label: 'Description', type: 'textarea',
      placeholder: 'Describe in your own words' },
    { key: 'important_people', label: 'Key People Involved', type: 'text' },
    { key: 'notes', label: 'Notes', type: 'textarea' },
  ],
  'financial-overview': [
    { key: 'account_type', label: 'Account Type', type: 'select',
      options: ['Bank Account - Checking', 'Bank Account - Savings', 'Brokerage Account',
                'Retirement - IRA', 'Retirement - 401k/403b', 'Retirement - Roth IRA',
                'Annuity', 'Life Insurance', 'Long-Term Care Insurance',
                'Umbrella Policy', 'Property Insurance', 'Safe Deposit Box',
                'Physical Safe', 'Loan/Line of Credit', 'Mortgage', 'Other'] },
    { key: 'institution', label: 'Institution/Company', type: 'text' },
    { key: 'account_number', label: 'Account Number', type: 'text', sensitive: true },
    { key: 'account_owner', label: 'Account Owner/Title', type: 'text' },
    { key: 'beneficiary', label: 'Named Beneficiary', type: 'text' },
    { key: 'contact_name', label: 'Contact Person', type: 'text' },
    { key: 'contact_phone', label: 'Contact Phone', type: 'phone' },
    { key: 'approximate_value', label: 'Approximate Value', type: 'text' },
    { key: 'location_of_documents', label: 'Where Are the Documents?', type: 'text' },
    { key: 'notes', label: 'Notes', type: 'textarea' },
  ],
  'digital-life': [
    { key: 'account_type', label: 'Type', type: 'select',
      options: ['Email Account', 'Cloud Storage', 'Social Media', 'Financial - Online',
                'Cryptocurrency Wallet', 'Password Manager', 'Subscription Service',
                'Automatic Payment', 'Website/Domain', 'Other'] },
    { key: 'service_name', label: 'Service/Platform', type: 'text' },
    { key: 'username', label: 'Username/Email', type: 'text', sensitive: true },
    { key: 'password_hint', label: 'Password Hint or Location', type: 'text', sensitive: true },
    { key: 'two_factor_method', label: '2FA Method', type: 'select',
      options: ['None', 'Authenticator App', 'SMS', 'Email', 'Hardware Key', 'Other'] },
    { key: 'recovery_info', label: 'Recovery Method/Backup Codes Location', type: 'text', sensitive: true },
    { key: 'monthly_cost', label: 'Monthly Cost', type: 'text' },
    { key: 'action_on_death', label: 'What Should Happen to This Account?', type: 'select',
      options: ['Close/Delete', 'Transfer to someone', 'Memorialize', 'Keep active', 'Cancel subscription', 'No preference'] },
    { key: 'transfer_to', label: 'Transfer To (if applicable)', type: 'text' },
    { key: 'notes', label: 'Notes', type: 'textarea' },
  ],
  'income-obligations': [
    { key: 'stream_type', label: 'Type', type: 'select',
      options: ['Pension', 'Social Security', 'Annuity Income', 'Rental Income',
                'Trust Distribution', 'Charitable Pledge', 'Household Bills',
                'Staff Payroll', 'Club Dues', 'Tax Payments', 'Other Income', 'Other Obligation'] },
    { key: 'source_or_payee', label: 'Source/Payee', type: 'text' },
    { key: 'amount', label: 'Amount', type: 'text' },
    { key: 'frequency', label: 'Frequency', type: 'select',
      options: ['Monthly', 'Quarterly', 'Semi-annually', 'Annually', 'One-time', 'Irregular'] },
    { key: 'payment_method', label: 'Payment Method', type: 'select',
      options: ['Direct deposit', 'Auto-pay', 'Check', 'Wire', 'Manual payment', 'Other'] },
    { key: 'account_charged', label: 'Account Charged/Deposited', type: 'text' },
    { key: 'contact', label: 'Contact Person', type: 'text' },
    { key: 'notes', label: 'Notes', type: 'textarea' },
  ],
  'business-interests': [
    { key: 'interest_type', label: 'Type', type: 'select',
      options: ['Active Business', 'Passive Investment', 'Private Equity Fund',
                'Real Estate Entity', 'Board Position - Corporate', 'Board Position - Nonprofit',
                'Trustee Role', 'Executor Appointment', 'Intellectual Property',
                'Licensing Agreement', 'Franchise', 'Other'] },
    { key: 'entity_name', label: 'Entity/Organization Name', type: 'text' },
    { key: 'entity_type', label: 'Entity Type', type: 'select',
      options: ['LLC', 'S-Corp', 'C-Corp', 'Partnership', 'LP', 'LLP', 'Sole Proprietorship',
                'Trust', 'Nonprofit', 'N/A', 'Other'] },
    { key: 'state_of_formation', label: 'State of Formation', type: 'text' },
    { key: 'ein', label: 'EIN', type: 'text', sensitive: true },
    { key: 'ownership_percentage', label: 'Ownership Percentage', type: 'text' },
    { key: 'co_owners', label: 'Co-Owners/Partners', type: 'textarea' },
    { key: 'registered_agent', label: 'Registered Agent', type: 'text' },
    { key: 'buy_sell_agreement', label: 'Buy-Sell Agreement?', type: 'boolean' },
    { key: 'succession_plan', label: 'Succession Plan Details', type: 'textarea' },
    { key: 'key_person_insurance', label: 'Key Person Insurance?', type: 'boolean' },
    { key: 'day_to_day_contact', label: 'Who Runs Day-to-Day Operations?', type: 'text' },
    { key: 'business_attorney', label: 'Business Attorney', type: 'text' },
    { key: 'business_cpa', label: 'Business CPA', type: 'text' },
    { key: 'capital_call_obligations', label: 'Outstanding Capital Call Obligations', type: 'text' },
    { key: 'valuation_date', label: 'Last Valuation Date', type: 'date' },
    { key: 'valuation_amount', label: 'Last Valuation Amount', type: 'text' },
    { key: 'exit_strategy', label: 'Desired Exit Strategy', type: 'textarea' },
    { key: 'critical_first_48hrs', label: 'What Needs to Happen in the First 48 Hours If You Are Incapacitated?', type: 'textarea' },
    { key: 'document_location', label: 'Where Are the Governing Documents?', type: 'text' },
    { key: 'notes', label: 'Notes', type: 'textarea' },
  ],
  'royalties': [
    { key: 'royalty_type', label: 'Type', type: 'select',
      options: ['Book/Publication', 'Music/Performance Rights', 'Oil/Gas/Mineral Rights',
                'Timber Rights', 'Patent Licensing', 'Software Licensing',
                'Image/Likeness Rights', 'Franchise Royalty', 'Other'] },
    { key: 'source', label: 'Source/Title', type: 'text' },
    { key: 'managing_entity', label: 'Managing Entity/Administrator', type: 'text' },
    { key: 'contact_name', label: 'Contact Person', type: 'text' },
    { key: 'contact_phone', label: 'Contact Phone', type: 'phone' },
    { key: 'payment_schedule', label: 'Payment Schedule', type: 'select',
      options: ['Monthly', 'Quarterly', 'Semi-annually', 'Annually', 'Irregular'] },
    { key: 'payment_method', label: 'How Payments Are Received', type: 'text' },
    { key: 'approximate_annual_income', label: 'Approximate Annual Income', type: 'text' },
    { key: 'contract_duration', label: 'Contract Duration/Expiration', type: 'text' },
    { key: 'transferable', label: 'Transferable to Heirs?', type: 'select',
      options: ['Yes - automatically', 'Yes - requires assignment', 'No - terminates at death', 'Unknown'] },
    { key: 'tax_treatment', label: 'Tax Treatment Notes', type: 'textarea' },
    { key: 'agreement_location', label: 'Where Is the Agreement Stored?', type: 'text' },
    { key: 'notes', label: 'Notes', type: 'textarea' },
  ],
  'personal-property': [
    { key: 'item_category', label: 'Category', type: 'select',
      options: ['Jewelry & Watches', 'Art & Paintings', 'Sculptures', 'Antiques',
                'Vehicles & Classic Cars', 'Watercraft', 'Wine & Spirits Collection',
                'Coins & Stamps', 'Memorabilia', 'Musical Instruments',
                'Books & First Editions', 'Other Collections', 'Other'] },
    { key: 'description', label: 'Description', type: 'textarea' },
    { key: 'appraised_value', label: 'Appraised Value', type: 'text' },
    { key: 'appraisal_date', label: 'Last Appraisal Date', type: 'date' },
    { key: 'appraiser', label: 'Appraiser/Dealer', type: 'text' },
    { key: 'location', label: 'Current Location', type: 'text' },
    { key: 'insurance_rider', label: 'Insurance Rider?', type: 'boolean' },
    { key: 'provenance', label: 'Provenance/History/Story', type: 'textarea' },
    { key: 'primary_beneficiary', label: 'Desired Recipient', type: 'text' },
    { key: 'alternate_beneficiary', label: 'Alternate Recipient', type: 'text' },
    { key: 'if_nobody_wants', label: 'If Nobody Wants It', type: 'select',
      options: ['Sell at auction', 'Sell through dealer', 'Donate to museum/charity', 'Dispose of', 'Other'] },
    { key: 'must_not_go_to', label: 'Must NOT Go To (if applicable)', type: 'text' },
    { key: 'photos', label: 'Photos', type: 'file' },
    { key: 'notes', label: 'Notes', type: 'textarea' },
  ],
  'firearms': [
    { key: 'make', label: 'Make', type: 'text' },
    { key: 'model', label: 'Model', type: 'text' },
    { key: 'serial_number', label: 'Serial Number', type: 'text', sensitive: true },
    { key: 'caliber_gauge', label: 'Caliber/Gauge', type: 'text' },
    { key: 'firearm_type', label: 'Type', type: 'select',
      options: ['Handgun', 'Rifle', 'Shotgun', 'NFA Item (SBR)', 'NFA Item (Suppressor)',
                'NFA Item (Full Auto)', 'Antique/Curio', 'Other'] },
    { key: 'location', label: 'Location', type: 'text' },
    { key: 'safe_info', label: 'Safe Combination/Key Location', type: 'text', sensitive: true },
    { key: 'nfa_registered', label: 'NFA Registered?', type: 'boolean' },
    { key: 'form4_info', label: 'Form 4 / Tax Stamp Info', type: 'text' },
    { key: 'concealed_carry', label: 'Concealed Carry Permit State(s)', type: 'text' },
    { key: 'desired_recipient', label: 'Desired Recipient', type: 'text' },
    { key: 'recipient_can_legally_receive', label: 'Can Recipient Legally Receive?', type: 'select',
      options: ['Yes', 'No', 'Unknown - needs verification'] },
    { key: 'notes', label: 'Notes', type: 'textarea' },
  ],
  'funeral-burial': [
    { key: 'preference_type', label: 'Type', type: 'select',
      options: ['Burial vs. Cremation', 'Cemetery/Location', 'Funeral Home',
                'Religious/Cultural Traditions', 'Memorial Service Wishes',
                'Obituary Preferences', 'Organ/Tissue Donation',
                'Music/Readings', 'Who Should Speak', 'Draft Obituary', 'Other'] },
    { key: 'description', label: 'Description', type: 'textarea' },
    { key: 'provider_name', label: 'Provider/Facility Name', type: 'text' },
    { key: 'provider_phone', label: 'Phone', type: 'phone' },
    { key: 'pre_paid', label: 'Pre-Paid?', type: 'boolean' },
    { key: 'contract_location', label: 'Where Is the Contract/Documentation?', type: 'text' },
    { key: 'notes', label: 'Notes', type: 'textarea' },
  ],
  'personal-wishes': [
    { key: 'wish_type', label: 'Type', type: 'select',
      options: ['Ethical Will / Legacy Letter', 'Life Lessons & Values',
                'Family Stories to Preserve', 'Charitable Legacy Intentions',
                'Specific Bequests Not in Trust', 'Messages to Individuals',
                'Hopes for the Family', 'Other'] },
    { key: 'title', label: 'Title', type: 'text' },
    { key: 'content', label: 'Content', type: 'rich_text' },
    { key: 'intended_for', label: 'Intended For', type: 'text' },
    { key: 'notes', label: 'Notes', type: 'textarea' },
  ],
  'home-property': [
    { key: 'property_type', label: 'Type', type: 'select',
      options: ['Primary Residence', 'Secondary/Vacation Home', 'Alarm System',
                'Safe/Vault', 'Generator', 'Pool/Spa', 'Irrigation System',
                'Vehicle', 'Storage Unit', 'Staff/Vendor', 'Seasonal Instructions', 'Other'] },
    { key: 'description', label: 'Description', type: 'textarea' },
    { key: 'location_address', label: 'Address/Location', type: 'text' },
    { key: 'access_codes', label: 'Access Codes/Combinations', type: 'text', sensitive: true },
    { key: 'contact_name', label: 'Contact Person/Vendor', type: 'text' },
    { key: 'contact_phone', label: 'Contact Phone', type: 'phone' },
    { key: 'schedule', label: 'Schedule/Frequency', type: 'text' },
    { key: 'notes', label: 'Notes', type: 'textarea' },
  ],
  'clubs-memberships': [
    { key: 'membership_type', label: 'Type', type: 'select',
      options: ['Country Club', 'Yacht Club', 'Golf Club', 'Social Club',
                'Board Position', 'Volunteer Commitment', 'Season Tickets',
                'Reserved Seating', 'Other'] },
    { key: 'organization', label: 'Organization Name', type: 'text' },
    { key: 'membership_number', label: 'Membership Number', type: 'text' },
    { key: 'contact', label: 'Contact Person', type: 'text' },
    { key: 'contact_phone', label: 'Contact Phone', type: 'phone' },
    { key: 'annual_cost', label: 'Annual Cost/Dues', type: 'text' },
    { key: 'transferable', label: 'Transferable?', type: 'select',
      options: ['Yes', 'No', 'With board approval', 'Unknown'] },
    { key: 'transfer_value', label: 'Transfer/Resale Value', type: 'text' },
    { key: 'notes', label: 'Notes', type: 'textarea' },
  ],
  'travel-lifestyle': [
    { key: 'item_type', label: 'Type', type: 'select',
      options: ['Frequent Flyer Program', 'Hotel Loyalty Program', 'Travel Agent',
                'Concierge Service', 'Timeshare', 'Vacation Property',
                'Planned Trip', 'Standing Reservation', 'Other'] },
    { key: 'program_name', label: 'Program/Service Name', type: 'text' },
    { key: 'account_number', label: 'Account/Membership Number', type: 'text' },
    { key: 'contact', label: 'Contact', type: 'text' },
    { key: 'contact_phone', label: 'Contact Phone', type: 'phone' },
    { key: 'balance_points', label: 'Points/Miles Balance', type: 'text' },
    { key: 'notes', label: 'Notes', type: 'textarea' },
  ],
}
